export const EXTRA_TITLES = {
  folio: 'folio — a local file, filed',
  ledger: 'ledger — addresses, not drawers',
  keelson: 'keelson — a handoff, not a drawer',
  garboard: 'garboard — a seam between two drops',
  capstan: 'capstan — a watch, not a drawer',
  treenail: 'treenail — a pin, not a drawer',
  fairlead: 'fairlead — a checklist, not a drawer',
  deadeye: 'deadeye — a witness, not a drawer',
  hounds: 'hounds — a line, not a drawer',
  seizing: 'seizing — a pile on one line',
  sounding: 'sounding — a reading, not a drawer',
  marline: 'marline — a log line, not a drawer',
  orlop: 'orlop — a locker under the vault',
  cleat: 'cleat — an address on the rail',
  shuttle: 'shuttle — a local file, carried',
  passage: 'passage — a named handoff',
  lantern: 'lantern — a short note, not a file',
  loft: 'loft — a local file, on the wall',
  quay: 'quay — a link, not a drawer',
  belaying: 'belaying — a pin, not a drawer',
};
export const EXTRA_DESC = {
  folio: 'Drop a local file into the share table. Discord unfurls /s. Large drops are warned, never refused.',
  ledger: 'Pin an address on the links shelf. Not a file cabinet. Discord unfurls /ledger.',
  keelson: 'Hand a local file to someone by name. Bytes land in the share table. The receipt lives beside it. Discord unfurls /keelson.',
  garboard: 'Note the seam between two files already filed. Not another vault. Discord unfurls /garboard.',
  capstan: 'Name a watch and pin a note. An optional local file still lands in the share table. Discord unfurls /capstan.',
  treenail: 'Name why a drop exists. An optional local file lands in the share table. Discord unfurls /treenail and /s. Large files are warned, never refused.',
  fairlead: 'A short checklist with an optional proof file. The file lands in the share table. Discord unfurls /fairlead. Large files are warned, never refused.',
  deadeye: 'Name who saw the file and write one line. The local drop lands in the deadeyes table. Discord unfurls /deadeye. Large files are warned, never refused.',
  hounds: 'Pair a line with a local file. Discord unfurls /hounds. Large files are warned, never refused.',
  seizing: 'File several local drops onto one line. Discord unfurls each row. Large files are warned, never refused.',
  sounding: 'Ask an address once and keep the status. Not a file cabinet. Discord unfurls /sounding.',
  marline: 'Write a watch log and file a local drop into the share table. Discord unfurls /marline. Large files are warned, never refused.',
  orlop: 'Hand a local file to someone by name. Bytes land in the share table. The receipt lives in handoffs. Discord unfurls /orlop. Large files are warned, never refused.',
  cleat: 'Pin an address with a note. Not a file cabinet. Discord unfurls /cleat.',
  shuttle: 'Carry a local file into the share table. Discord unfurls /shuttle and /s. Large files are warned, never refused.',
  passage: 'Hand a local file to a name. Bytes land in the share table. The slip lives in passages. Discord unfurls /passage. Large files are warned, never refused.',
  lantern: 'Leave a short note on the whispers table. Not a file cabinet. Discord unfurls /lantern.',
  loft: 'Hang a local file on a titled board. Bytes land in the share table. Discord unfurls /loft. Large files are warned, never refused.',
  quay: 'A public log of drops already in the share table. Discord unfurls /quay.',
  belaying: 'Pin a link on the rail. Not a file cabinet. Discord unfurls /belaying.',
};
