export const EXTRA_TITLES = {
  fiferail: 'fiferail — a file on the rail',
  gantline: 'gantline — an address, not a drawer',
  luff: 'luff — a sail angle, not a drawer',
  ketch: 'ketch — two masts, not a drawer',
  beacon: 'beacon — a lit signal, not a drawer',
  bowsprit: 'bowsprit — a forward, not a drawer',
  chainplate: 'chainplate — a load, not a drawer',
  wharf: 'wharf — a tide berth, not a drawer',
  lashing: 'lashing — a knot, not a drawer',
  wale: 'wale — rankvault',
  flemish: 'flemish — rankvault',
  kedge: 'kedge — an anchor, not a drawer',
  binnacle: 'binnacle — a compass, not a drawer',
  rabbet: 'rabbet — a groove, not a drawer',
  floors: 'floors — a frame survey, not a drawer',
  chestree: 'chestree — a mast partner, not a drawer',
  kevel: 'kevel — an open window, not a drawer',
  thwart: 'thwart — a receipt, not a drawer',
  bulwark: 'bulwark — a shield, not a drawer',
  coaming: 'coaming — a raised rim, not a drawer',
  bumkin: 'bumkin — a return date, not a drawer',
  washstrake: 'washstrake — a pair, not a drawer',
  waterway: 'waterway — a gutter, not a drawer',
  tumblehome: 'tumblehome — a lean, not a drawer',
  sheerstrake: 'sheerstrake — a letter, not a drawer',
  apostle: 'apostle — a spoken line, not a drawer',
  knee: 'knee — a join, not a drawer',
  transom: 'transom — a weighing, not a drawer',
  scupper: 'scupper — a drain, not a drawer',
  rider: 'rider — a brace, not a drawer',
  folio: 'folio — a local file, filed',
  ledger: 'ledger — addresses, not drawers',
  keelson: 'keelson — a handoff, not a drawer',
  garboard: 'garboard — a seam between two drops',
  capstan: 'capstan — a watch, not a drawer',
  treenail: 'treenail — a pin, not a drawer',
  fairlead: 'fairlead — a checklist, not a drawer',
  deadeye: 'deadeye — a witness, not a drawer',
  hounds: 'hounds — a line, not a drawer',
  seizing: 'seizing — a pile on one line',
  sounding: 'sounding — a reading, not a drawer',
  marline: 'marline — a log line, not a drawer',
  orlop: 'orlop — a locker under the vault',
  cleat: 'cleat — an address on the rail',
  shuttle: 'shuttle — a local file, carried',
  passage: 'passage — a named handoff',
  lantern: 'lantern — a short note, not a file',
  loft: 'loft — a local file, on the wall',
  quay: 'quay — a link, not a drawer',
  belaying: 'belaying — a pin, not a drawer',
  forepeak: 'forepeak — a local file, filed',
  lazarette: 'lazarette — public pictures, not a drawer',
  skylight: 'skylight — a color pane, not a drawer',
  limber: 'limber — a timed note, not a drawer',
  bitt: 'bitt — a file tied to the rail',
  taffrail: 'taffrail — a file and a strip of notes',
  counter: 'counter — a mark under the stern',
  gunwale: 'gunwale — a rail of files, not a drawer',
  futtock: 'futtock — a rib, not a drawer',
  stringer: 'stringer — a line, not a drawer',
  carvel: 'carvel — flush planks, not a drawer',
  bearding: 'bearding — a digest, not a drawer',
  rowlock: 'rowlock — a named handoff, not a drawer',
  margin: 'margin — a line beside a file, not a drawer',
  pintle: 'pintle — a hinge, not a drawer',
  stemson: 'stemson — a packing slip, not a drawer',
  lodging: 'lodging — a line overnight, not a file',
  oakum: 'oakum — a seam, not a drawer',
  painter: 'painter — a berth, not a drawer',
  davits: 'davits — a hoist, not a drawer',
  hawser: 'hawser — a tie, not a drawer',
  selvage: 'selvage — a sequence, not a drawer',
  vesper: 'vesper — a watch, not a drawer',
  hawsepipe: 'hawsepipe — a file pipe, not a drawer',
  stemhead: 'stemhead — a bow note, not a drawer',
  counterrail: 'counterrail — three seats, not a drawer',
};
export const EXTRA_DESC = {
  luff: 'Set a heading, write the wind, and hand a local file to the share table. The angle is a note, not a cabinet. Discord unfurls /luff and /s. Large files are warned, never refused.',
  ketch: 'Hand two local files into the share table and write which mast carries what. Discord unfurls /ketch and each /s. Large files are warned, never refused.',
  beacon: 'Light a line with an optional fade time and an optional local file. The fade is a note, not a lock. Discord unfurls /beacon and /s. Large files are warned, never refused.',
  bowsprit: 'Name a port and an arrival note, then hand a local file to the share table. The spar is a forward, not a cabinet. Discord unfurls /bowsprit and /s. Large files are warned, never refused.',
  chainplate: 'Write the load a file is holding and who is on the other end. Bytes land in the share table. Discord unfurls /chainplate and /s. Large files are warned, never refused.',
  wharf: 'Set a local file on a named berth with a collector and a tide note. Bytes land in the share table. Discord unfurls /wharf and /s. Large files are warned, never refused.',
  lashing: 'Lash a new local file to a share id that already landed. Not a vault drawer. Discord unfurls /lashing and /s. Large files are warned, never refused.',
  wale: 'Lay a named plank and hand a local file to the share table. The plank is a receipt, not a cabinet. Discord unfurls /wale and /s. Large files are warned, never refused.',
  flemish: 'Coil a title, a destination, and a blurb into a link card. Not a file drawer. Discord unfurls /flemish.',
  kedge: 'Name a hold and pin a destination. An optional local file lands in the share table. Discord unfurls /kedge and /s. Large files are warned, never refused.',
  binnacle: 'A compass of public drops already in the share table. Not another drawer. Discord unfurls /binnacle and /s.',
  rabbet: 'Cut a groove and seat an optional local file. Bytes land in the share table. Discord unfurls /rabbet and /s. Large files are warned, never refused.',
  floors: 'Survey a frame and file an optional photo. Bytes land in the share table. Discord unfurls /floors and /s. Large files are warned, never refused.',
  chestree: 'Seat a mast partner and an optional local file. Bytes land in the share table. Discord unfurls /chestree and /s. Large files are warned, never refused.',
  kevel: 'Belay a local file into the share table and leave an open window. The window is a note, not a lock. Discord unfurls /kevel and /s. Large files are warned, never refused.',
  thwart: 'File a local drop into the share table and keep a receipt. Not a vault drawer. Discord unfurls /thwart and /s. Large files are warned, never refused.',
  bulwark: 'File a local drop into the share table and name what it holds against. Not a vault drawer. Discord unfurls /bulwark and /s. Large files are warned, never refused.',
  coaming: 'Raise a rim note. An optional local file lands in the share table. Discord unfurls /coaming and /s.',
  washstrake: 'Hand two local files into the share table and write how they differ. Discord unfurls /washstrake and /s. Large files are warned, never refused.',
  waterway: 'Cut a gutter note. An optional local file lands in the share table. Discord unfurls /waterway and /s.',
  tumblehome: 'Hand a local file across with a lean note. Bytes land in the share table. Discord unfurls /tumblehome and /s. Large files are warned, never refused.',
  sheerstrake: 'File a cover letter in its own table. An optional local attachment lands in the share table. Discord unfurls /sheerstrake and /s.',
  bumkin: 'Hand a local file across with a return-by. Not a vault drawer. Discord unfurls /bumkin and /s. Large files are warned, never refused.',
  apostle: 'File a local drop and leave one spoken line with a witness. Not a vault drawer. Discord unfurls /apostle and /s. Large files are warned, never refused.',
  knee: 'File a local drop into the share table and keep who it braces. Not a vault drawer. Discord unfurls /knee and /s. Large files are warned, never refused.',
  transom: 'Weigh two shares that already landed. Not a vault drawer. Discord unfurls /transom.',
  scupper: 'File one local drop into the share table and write what should drain beside it. Not a vault drawer. Discord unfurls /scupper and /s. Large files are warned, never refused.',
  rider: 'Name a timber and file one local drop into the share table. The brace note lives beside it. Discord unfurls /rider and /s. Large files are warned, never refused.',
  folio: 'Drop a local file into the share table. Discord unfurls /s. Large drops are warned, never refused.',
  ledger: 'Pin an address on the links shelf. Not a file cabinet. Discord unfurls /ledger.',
  keelson: 'Hand a local file to someone by name. Bytes land in the share table. The receipt lives beside it. Discord unfurls /keelson.',
  garboard: 'Note the seam between two files already filed. Not another vault. Discord unfurls /garboard.',
  capstan: 'Name a watch and pin a note. An optional local file still lands in the share table. Discord unfurls /capstan.',
  treenail: 'Name why a drop exists. An optional local file lands in the share table. Discord unfurls /treenail and /s. Large files are warned, never refused.',
  fairlead: 'A short checklist with an optional proof file. The file lands in the share table. Discord unfurls /fairlead. Large files are warned, never refused.',
  deadeye: 'Name who saw the file and write one line. The local drop lands in the deadeyes table. Discord unfurls /deadeye. Large files are warned, never refused.',
  hounds: 'Pair a line with a local file. Discord unfurls /hounds. Large files are warned, never refused.',
  seizing: 'File several local drops onto one line. Discord unfurls each row. Large files are warned, never refused.',
  sounding: 'Ask an address once and keep the status. Not a file cabinet. Discord unfurls /sounding.',
  marline: 'Write a watch log and file a local drop into the share table. Discord unfurls /marline. Large files are warned, never refused.',
  orlop: 'Hand a local file to someone by name. Bytes land in the share table. The receipt lives in handoffs. Discord unfurls /orlop. Large files are warned, never refused.',
  cleat: 'Pin an address with a note. Not a file cabinet. Discord unfurls /cleat.',
  shuttle: 'Carry a local file into the share table. Discord unfurls /shuttle and /s. Large files are warned, never refused.',
  passage: 'Hand a local file to a name. Bytes land in the share table. The slip lives in passages. Discord unfurls /passage. Large files are warned, never refused.',
  lantern: 'Leave a short note on the whispers table. Not a file cabinet. Discord unfurls /lantern.',
  loft: 'Hang a local file on a titled board. Bytes land in the share table. Discord unfurls /loft. Large files are warned, never refused.',
  quay: 'A public log of drops already in the share table. Discord unfurls /quay.',
  belaying: 'Pin a link on the rail. Not a file cabinet. Discord unfurls /belaying.',
  forepeak: 'Drop a local file straight into the share table. Discord unfurls /forepeak and /s. Large files are warned, never refused.',
  lazarette: 'A gallery of image drops already in the share table. Not a vault drawer. Discord unfurls /lazarette.',
  skylight: 'Sample a still and publish only the color pane. Discord unfurls /skylight and /s.',
  limber: 'Time a note in the tab, then file the markdown in the share table. Discord unfurls /limber and /s. Long notes are warned, never refused.',
  bitt: 'Tie a local file to the share table and pin the Discord card on the rail. Not a vault drawer. Large files are warned, never refused.',
  taffrail: 'File a local drop, then leave short notes beside it. Bytes land in the share table. Notes live in taffrail_notes. Discord unfurls /taffrail and /s. Large files are warned, never refused.',
  counter: 'File one local drop into the share table and stamp a countermark beside it. Not a vault drawer. Discord unfurls /counter and /s. Large files are warned, never refused.',
  gunwale: 'File several local drops into the share table and keep them on one rail. Discord unfurls /gunwale and each /s. Large files are warned, never refused.',
  futtock: 'File a local drop into the share table and keep a rib note with its fingerprint. Discord unfurls /futtock and /s. Large files are warned, never refused.',
  stringer: 'Lay a short line beside a share that already landed. Not a vault drawer. Discord unfurls /stringer.',
  carvel: 'Lay two or more local files flush and write the seam. Each file lands in the share table. Discord unfurls /carvel and /s. Large files are warned, never refused.',
  bearding: 'File a local drop and keep its sha-256 beside it. Bytes land in the share table. Discord unfurls /bearding and /s. Large files are warned, never refused.',
  rowlock: 'Hand one local file to a named keeper. Bytes land in the share table. The handoff lives in rowlocks. Discord unfurls /rowlock and /s. Large files are warned, never refused.',
  margin: 'Leave a line beside a share that already landed. Not a file cabinet. Discord unfurls /margin and /s.',
  pintle: 'Pin a local file to a purpose and say which way it opens. Bytes land in the share table. The hinge lives in pintles. Discord unfurls /pintle and /s. Large files are warned, never refused.',
  stemson: 'Print a packing slip for a local file. Bytes land in the share table. The slip keeps a handling note, a recipient, and a sha-256. Discord unfurls /stemson and /s. Large files are warned, never refused.',
  lodging: 'Leave a short line overnight with an optional wake time. Not a file cabinet. The time is a note, not a lock. Discord unfurls /lodging.',
  oakum: 'Stuff a seam between one or two local files. Bytes land in the share table. Discord unfurls /oakum and /s. Large files are warned, never refused.',
  painter: 'Tie a berth, a holder, and an optional local file. Bytes land in the share table. Discord unfurls /painter and /s. Large files are warned, never refused.',
  davits: 'Hoist a local file off the dock into the share table. Discord unfurls /davits and /s. Large files are warned, never refused.',
  hawser: 'Tie an address to a local file. Discord unfurls /hawser and /s. Large files are warned, never refused.',
  selvage: 'Arrange local files into a sequence. Each frame lands in the share table. Discord unfurls /selvage. Large files are warned, never refused.',
  vesper: 'Ring a time and a line on the watch board. Not a file cabinet. Discord unfurls /vesper.',
  hawsepipe: 'Hand a local file through the pipe into the quay table, then a public card. Discord unfurls /hawsepipe and /s. Large files are warned, never refused.',
  stemhead: 'Write a note at the bow and publish it as markdown. Not a cabinet. Discord unfurls /stemhead and /s.',
  counterrail: 'Three seats of notes on this device. Publish the rail if you want a Discord card. Not a file drawer.',
  fiferail: 'Hang a local file on the rail. Bytes land in the share table. Discord unfurls /fiferail and /s. Large files are warned, never refused.',
  gantline: 'Pin an address and a note. Not a file cabinet. Discord unfurls /gantline.',
};
