import { useState, useRef, useEffect } from 'react';
import { useAuth } from './AuthContext';
import { useRouter, type Route } from './Router';

type NavItem = { to: Route; label: string };

const primary: NavItem[] = [
  { to: 'vault', label: 'vault' },
  { to: 'drop', label: 'drop' },
  { to: 'cider', label: 'cider' },
  { to: 'merlon', label: 'merlon' },
  { to: 'tarn', label: 'tarn' },
  { to: 'ferrule', label: 'ferrule' },
  { to: 'skiff', label: 'skiff' },
  { to: 'jetty', label: 'jetty' },
  { to: 'cloister', label: 'cloister' },
  { to: 'mullion', label: 'mullion' },
  { to: 'folio', label: 'folio' },
  { to: 'gilt', label: 'gilt' },
];

const groups: { title: string; items: NavItem[] }[] = [
  {
    title: 'files',
    items: [
      { to: 'vault', label: 'vault' },
      { to: 'drop', label: 'drop' },
      { to: 'ferrule', label: 'ferrule' },
      { to: 'merlon', label: 'merlon' },
      { to: 'skiff', label: 'skiff' },
      { to: 'jetty', label: 'jetty' },
      { to: 'mullion', label: 'mullion' },
      { to: 'saddle', label: 'saddle' },
      { to: 'emberglass', label: 'emberglass' },
      { to: 'driftnet', label: 'driftnet' },
      { to: 'folio', label: 'folio' },
      { to: 'mason', label: 'mason' },
      { to: 'whet', label: 'whet' },
      { to: 'rafter', label: 'rafter' },
      { to: 'gauge', label: 'gauge' },
      { to: 'loft', label: 'loft' },
      { to: 'gnomon', label: 'gnomon' },
      { to: 'thimble', label: 'thimble' },
      { to: 'kindling', label: 'kindling' },
      { to: 'nave', label: 'nave' },
      { to: 'lattice', label: 'lattice' },
      { to: 'slip', label: 'slip' },
      { to: 'pinnacle', label: 'pinnacle' },
      { to: 'waymark', label: 'waymark' },
      { to: 'harvest', label: 'harvest' },
      { to: 'wellspring', label: 'wellspring' },
      { to: 'solarium', label: 'solarium' },
      { to: 'vestibule', label: 'vestibule' },
      { to: 'keystone', label: 'keystone' },
      { to: 'lintel', label: 'lintel' },
      { to: 'terrace', label: 'terrace' },
      { to: 'sundial', label: 'sundial' },
      { to: 'cistern', label: 'cistern' },
      { to: 'plinth', label: 'plinth' },
      { to: 'rookery', label: 'rookery' },
      { to: 'scrip', label: 'scrip' },
      { to: 'silo', label: 'silo' },
      { to: 'ridge', label: 'ridge' },
      { to: 'pallet', label: 'pallet' },
      { to: 'tandem', label: 'tandem' },
      { to: 'tide', label: 'tide' },
      { to: 'convoy', label: 'convoy' },
      { to: 'portage', label: 'portage' },
      { to: 'vale', label: 'vale' },
      { to: 'harbor', label: 'harbor' },
      { to: 'wick', label: 'wick' },
      { to: 'nest', label: 'nest' },
      { to: 'kiln', label: 'kiln' },
      { to: 'meadow', label: 'meadow' },
      { to: 'parcel', label: 'parcel' },
      { to: 'nimbus', label: 'nimbus' },
      { to: 'manor', label: 'manor' },
      { to: 'locket', label: 'locket' },
      { to: 'relic', label: 'relic' },
      { to: 'keel', label: 'keel' },
      { to: 'spool', label: 'spool' },
      { to: 'sluice', label: 'sluice' },
      { to: 'pebble', label: 'pebble' },
      { to: 'pollen', label: 'pollen' },
      { to: 'gully', label: 'gully' },
      { to: 'glacier', label: 'glacier' },
      { to: 'quarry', label: 'quarry' },
      { to: 'spire', label: 'spire' },
      { to: 'lagoon', label: 'lagoon' },
      { to: 'keepsake', label: 'keepsake' },
    ],
  },
  {
    title: 'share',
    items: [
      { to: 'cloister', label: 'cloister' },
      { to: 'cider', label: 'cider' },
      { to: 'tarn', label: 'tarn' },
      { to: 'merlon', label: 'merlon' },
      { to: 'skiff', label: 'skiff' },
      { to: 'jetty', label: 'jetty' },
      { to: 'gilt', label: 'gilt' },
      { to: 'saddle', label: 'saddle' },
      { to: 'emberglass', label: 'emberglass' },
      { to: 'driftnet', label: 'driftnet' },
      { to: 'folio', label: 'folio' },
      { to: 'mason', label: 'mason' },
      { to: 'relay', label: 'relay' },
      { to: 'quilt', label: 'quilt' },
      { to: 'catalog', label: 'catalog' },
      { to: 'laneway', label: 'laneway' },
      { to: 'kindling', label: 'kindling' },
      { to: 'nave', label: 'nave' },
      { to: 'spur', label: 'spur' },
      { to: 'ripple', label: 'ripple' },
      { to: 'stillroom', label: 'stillroom' },
      { to: 'hearth', label: 'hearth' },
      { to: 'oxbow', label: 'oxbow' },
      { to: 'aegis', label: 'aegis' },
      { to: 'slate', label: 'slate' },
      { to: 'solace', label: 'solace' },
      { to: 'horizon', label: 'horizon' },
      { to: 'mirage', label: 'mirage' },
      { to: 'gazette', label: 'gazette' },
      { to: 'bazaar', label: 'bazaar' },
      { to: 'atoll', label: 'atoll' },
      { to: 'kite', label: 'kite' },
      { to: 'isthmus', label: 'isthmus' },
      { to: 'grove', label: 'grove' },
      { to: 'pinion', label: 'pinion' },
      { to: 'lark', label: 'lark' },
      { to: 'inlet', label: 'inlet' },
      { to: 'ticker', label: 'ticker' },
      { to: 'pulse', label: 'pulse' },
      { to: 'hush', label: 'hush' },
      { to: 'orbit', label: 'orbit' },
      { to: 'signal', label: 'signal' },
      { to: 'ledger', label: 'ledger' },
      { to: 'glyph', label: 'glyph' },
      { to: 'quay', label: 'quay' },
      { to: 'zinc', label: 'zinc' },
      { to: 'lumen', label: 'lumen' },
      { to: 'wisp', label: 'wisp' },
      { to: 'vesper', label: 'vesper' },
      { to: 'rill', label: 'rill' },
      { to: 'solstice', label: 'solstice' },
      { to: 'lantern', label: 'lantern' },
      { to: 'reef', label: 'reef' },
      { to: 'lichen', label: 'lichen' },
      { to: 'moss', label: 'moss' },
      { to: 'lattice', label: 'lattice' },
      { to: 'slip', label: 'slip' },
    ],
  },
  {
    title: 'create',
    items: [
      { to: 'mullion', label: 'mullion' },
      { to: 'cider', label: 'cider' },
      { to: 'thimble', label: 'thimble' },
      { to: 'stillroom', label: 'stillroom' },
      { to: 'nook', label: 'nook' },
      { to: 'iris', label: 'iris' },
      { to: 'filament', label: 'filament' },
      { to: 'slate', label: 'slate' },
      { to: 'octave', label: 'octave' },
      { to: 'halo', label: 'halo' },
      { to: 'sable', label: 'sable' },
      { to: 'studio', label: 'studio' },
      { to: 'saffron', label: 'saffron' },
      { to: 'bramble', label: 'bramble' },
      { to: 'vellum', label: 'vellum' },
      { to: 'opal', label: 'opal' },
      { to: 'thorn', label: 'thorn' },
      { to: 'marrow', label: 'marrow' },
      { to: 'notes', label: 'notes' },
      { to: 'paste', label: 'paste' },
      { to: 'markdown', label: 'markdown' },
      { to: 'sketch', label: 'sketch' },
      { to: 'helix', label: 'helix' },
      { to: 'quill', label: 'quill' },
      { to: 'loom', label: 'loom' },
      { to: 'prism', label: 'prism' },
      { to: 'mosaic', label: 'mosaic' },
      { to: 'atelier', label: 'atelier' },
      { to: 'ledge', label: 'ledge' },
      { to: 'pavilion', label: 'pavilion' },
      { to: 'sanctum', label: 'sanctum' },
      { to: 'umber', label: 'umber' },
      { to: 'chapel', label: 'chapel' },
      { to: 'basin', label: 'basin' },
      { to: 'willow', label: 'willow' },
      { to: 'solace', label: 'solace' },
    ],
  },
  {
    title: 'tools',
    items: [
      { to: 'cloister', label: 'cloister' },
      { to: 'ferrule', label: 'ferrule' },
      { to: 'tarn', label: 'tarn' },
      { to: 'whet', label: 'whet' },
      { to: 'rafter', label: 'rafter' },
      { to: 'gilt', label: 'gilt' },
      { to: 'catalog', label: 'catalog' },
      { to: 'gauge', label: 'gauge' },
      { to: 'gnomon', label: 'gnomon' },
      { to: 'laneway', label: 'laneway' },
      { to: 'spur', label: 'spur' },
      { to: 'harvest', label: 'harvest' },
      { to: 'waymark', label: 'waymark' },
      { to: 'ripple', label: 'ripple' },
      { to: 'cistern', label: 'cistern' },
      { to: 'ridge', label: 'ridge' },
      { to: 'silo', label: 'silo' },
      { to: 'copper', label: 'copper' },
      { to: 'quartz', label: 'quartz' },
      { to: 'nadir', label: 'nadir' },
      { to: 'sieve', label: 'sieve' },
      { to: 'palette', label: 'palette' },
      { to: 'convert', label: 'convert' },
      { to: 'hash', label: 'hash' },
      { to: 'qr', label: 'qr' },
      { to: 'diff', label: 'diff' },
      { to: 'zip', label: 'zip' },
      { to: 'status', label: 'status' },
      { to: 'meridian', label: 'meridian' },
      { to: 'tempo', label: 'tempo' },
      { to: 'trestle', label: 'trestle' },
      { to: 'observatory', label: 'observatory' },
      { to: 'atrium', label: 'atrium' },
      { to: 'glacier', label: 'glacier' },
      { to: 'gully', label: 'gully' },
      { to: 'quarry', label: 'quarry' },
      { to: 'keepsake', label: 'keepsake' },
      { to: 'emberglass', label: 'emberglass' },
    ],
  },
];
