export const EXTRA_TITLES = {
  garland: 'garland — a file, with a colour on the card',
  partners: 'partners — a board, not a cabinet',
  washboard: 'washboard — rinse a local file into the share table',
  beakhead: 'beakhead — a handover, not a drawer',
  windlass: 'windlass — read the head, then file it',
  thole: 'thole — a pin for a person',
  transom: 'transom — a still, lifted',
  floorboard: 'floorboard — a preview, then a card',
  garboard: 'garboard — a memo, not a drawer',
  treenail: 'treenail — two files, one receipt',
  wales: 'wales — a reading list, filed',
  rudder: 'rudder — point it, then hand it over',
  bowsprit: 'bowsprit — a cover, then the file',
  skeg: 'skeg — a still, softened',
  gripe: 'gripe — a handover list',
  cringle: 'cringle — a ring, then a card',
  bowline: 'bowline — a knot you can hand over',
  kedge: 'kedge — a pin, optional file',
  topping: 'topping — a colour on the lift',
  topmark: 'topmark — one mark, several files',
  billet: 'billet — a slip for an address',
  gunnel: 'gunnel — what stays, what leaves',
  kevel: 'kevel — a file with a time on it',
  marline: 'marline — a caption on the still',
  fairlead: 'fairlead — an address, with a card',
  painter: 'painter — a colour on the discord card',
  oakum: 'oakum — a pack, filed one by one',
  scull: 'scull — a note rowed across',
  cleat: 'cleat — a tempo, not a drawer',
  lantern: 'lantern — a lamp for one sitting',
  splice: 'splice — two drafts, one card',
  quayage: 'quayage — a tally, not a vault',
  satchel: 'satchel — a pack, not a drawer',
  vitrine: 'vitrine — the public shelf',
  trammel: 'trammel — a timed drop',
  tiller: 'tiller — steer the discord card',
  lodestone: 'lodestone — a bearing, not a drawer',
  bosun: 'bosun — a watch, not a cabinet',
  hawse: 'hawse — a split, not a cabinet',
  deadeye: 'deadeye — a sitting, not a drawer',
  futtock: 'futtock — a colour ramp',
  sheer: 'sheer — a local file, filed',
  coping: 'coping — a contrast, not a drawer',
  archivolt: 'archivolt — chapter marks',
  arris: 'arris — one edge of the day',
  carling: 'carling — a pile, then an index',
  deadwood: 'deadwood — a hash, not the file',
  fashion: 'fashion — a cover discord can see',
  keel: 'keel — a reading mark, not a drawer',
  strake: 'strake — one local file, one card',
  coaming: 'coaming — a sitting, not a cabinet',
  spirketing: 'spirketing — a handover slip, not a drawer',
  manifest: 'manifest — several files, one handover',
  shelf: 'shelf — what already landed',
  courier: 'courier — a file with a time on it',
  vault: 'vault — files on this device',
  limber: 'limber — a pin, not a drawer',
  orlop: 'orlop — a board under the deck',
  chainplate: 'chainplate — a list that holds',
};

export const EXTRA_DESC = {
  garland: 'Pick a local file, stamp a colour, and file it into the share table. Discord unfurls /s. Large drops are warned, never refused.',
  partners: 'A shared board in its own table. An optional local file still lands in the share database. Discord unfurls the card. Not a cabinet.',
  washboard: 'Drop a local file into the share table and stamp a Discord accent. Large drops are warned, never refused. Paste /washboard or /s.',
  beakhead: 'A handover slip, plus an optional local file. Both land in the share table. Discord unfurls each card. Not a cabinet.',
  windlass: 'Read the first sixteen bytes of a local file, then file it into the share table. Discord unfurls /windlass and /s. Large drops are warned, never refused.',
  thole: 'A named slip. The line lands as a text row, and an optional local file rides as its own card. Discord unfurls both. Not a cabinet.',
  transom: 'Lift a local still in the tab and file the PNG. Image cards unfurl with the picture. Large stills are warned, never refused.',
  floorboard: 'Preview a local file in the tab, then file it into the share table. Discord unfurls /s and /floorboard. Large drops are warned, never refused.',
  garboard: 'Record a memo in the tab, or write the line. The audio lands in the share table. Discord unfurls the card. Long memos are warned, never refused.',
  treenail: 'Hash two local files and file the receipt. Discord unfurls same or different. The originals stay on your machine. Large pairs are warned, never refused.',
  wales: 'Stack addresses, then file one markdown list into the share table. Discord unfurls the card. Not a cabinet.',
  rudder: 'A heading, a note, and an optional local file filed into the share table. Discord unfurls the handover. Large drops are warned, never refused.',
  bowsprit: 'Write the Discord line, attach a local file if you have one, and file it into the share table. Large drops are warned, never refused.',
  skeg: 'Soften a local still in the tab, then file the PNG. Image cards unfurl with the picture. Large stills are warned, never refused.',
  gripe: 'A handover list. Filing writes a markdown receipt into the share table. Discord unfurls the card. Not a vault drawer.',
  cringle: 'Name the eye of a local file and file it. Discord unfurls the card. Large drops are warned, never refused.',
  bowline: 'Write a note in the tab. Filing turns it into a text drop. The /s link is the Discord card.',
  kedge: 'A pin in the desk table, with an optional local file in the share table. No size cutoff.',
  topping: 'Stamp a local file with a colour and a label, then file it. The card carries the colour.',
  topmark: 'Several local files land in the share table. Discord unfurls the pack note. Large packs are warned, never refused.',
  billet: 'An address on the links shelf, plus a one-line card Discord can unfurl. Not a file cabinet.',
  gunnel: 'Two columns — kept and sent — filed as one text drop. The /s link is the Discord card.',
  kevel: 'Pick a local file and a ready-by time. The bytes land in the share table. Discord unfurls the card. Large drops are warned, never refused.',
  marline: 'Burn a caption onto a still in the tab, then file the PNG. Image cards unfurls with the picture.',
  fairlead: 'Save a link on the quay and file a card Discord can unfurl. Optional cover. Not a cabinet.',
  painter: 'Pick a local file, write the card line, stamp a colour. Bytes land in the share table. Large drops are warned, never refused.',
  oakum: 'Each local file is written to the share database. The shelf keeps the list. Discord unfurls the first card.',
  scull: 'Open a local text file or type a note. Filing writes a real file into the share table and hands Discord a card.',
  cleat: 'A click in the tab. Filing the session writes a text note into the share table. Discord unfurls the card. Nothing is refused for size.',
  lantern: 'A warm timer for one sitting. File the note if you want a Discord card. Not a cabinet.',
  splice: 'Join two local texts and file the combined note. Discord unfurls /s. Large splices are warned, never cut.',
  quayage: 'A line tally that files as a receipt. Discord gets the card. Nothing is stored until you send it.',
  satchel: 'Pack local files into one parcel. Each file lands in the share database. Discord unfurls the pack. Large packs are warned, never refused.',
  vitrine: 'The public shelf of files already filed. Every card still unfurls on Discord.',
  trammel: 'Pick a local file, optional pass, optional ready-by. Bytes land in the share table. Discord unfurls /s. Slowness warning only.',
  tiller: 'Set the title, caption, and accent, then file a local file. Discord unfurls the card you steered. Large drops are warned, never refused.',
  lodestone: 'Save an address on the links shelf and file a text card Discord can unfurl. Not a cabinet.',
  bosun: 'A watch list in the tab. Filing writes one markdown drop. Discord unfurls the list. Not a vault drawer.',
  hawse: 'Split a bill in the tab. Filing writes the note, and an optional receipt, into the share database. Discord unfurls the card. Large slips are warned, never refused.',
  deadeye: 'A sitting timer. File the note if you want a Discord card. Not a cabinet.',
  futtock: 'Mix a colour ramp, then file it with an optional reference image. Discord takes the accent. Large references are warned, never refused.',
  reliquary: 'Drop a local file into the share database. Discord unfurls /s. Large drops are warned, never refused.',
  quoin: 'Set a reading measure in the tab. Filing writes the spec, not a cabinet. Discord unfurls the card.',
  wick: 'A sitting timer. File the note if you want a Discord card. Not a vault drawer.',
  sheer: 'Drop a local file into the share database. Discord unfurls /s. Large drops are warned, never refused.',
  coping: 'Check a colour pair in the tab. Filing writes the spec. Discord unfurls the card. Not a cabinet.',
  archivolt: 'Chapter marks stay in the browser until you file the list. Discord unfurls /s.',
  arris: 'A sitting timer. File the note if you want a Discord card. Not a vault drawer.',
  carling: 'Several local files land in the share table. Carling then files a markdown index of the Discord cards. Large piles are warned, never refused.',
  deadwood: 'Hash a local file in the tab and compare a pasted digest. Only the receipt is filed. The original stays on your machine.',
  fashion: 'Paint a 1200x630 cover and file the PNG so Discord unfurls a real image. An optional companion file rides along as its own row.',
  keel: 'A reading mark on its own shelf. Not a file cabinet. Discord unfurls /keel.',
  strake: 'One local file lands in the share database. Discord unfurls /s. Large drops are warned, never refused.',
  coaming: 'A twenty-five minute sitting. Notes go to the reading table, not the vault. Discord unfurls /coaming.',
  spirketing: 'A named slip with an optional local file. The file lands in the share table. Discord unfurls /spirket. Large files are warned, never refused.',
  manifest: 'Several local files land in the share table, then a pack row is written. Discord unfurls each /s card. Large packs are warned, never refused.',
  shelf: 'The public log of files already in the share table. Every card still unfurls on Discord.',
  courier: 'A local file with an optional passcode and expiry, filed into the share table. Discord unfurls /s. Slowness warning only.',
  vault: 'Files kept on this device. Public links still land in the share table. No size cap, only a warning if a drop may feel slow.',
  limber: 'Pin an address on the links shelf. An optional local file still lands in the share table. Discord unfurls /limber and /s. Large companions are warned, never refused.',
  orlop: 'A shared line board in its own table. Not a file cabinet. Discord unfurls /orlop.',
  chainplate: 'A shared tick list. Attach a local file only if the item needs one. Bytes land in the share table. Discord unfurls the card. No size cap.',
};
