export const EXTRA_TITLES = {
  cringle: 'cringle — a ring, then a card',
  bowline: 'bowline — a knot you can hand over',
  kedge: 'kedge — a pin, optional file',
  topping: 'topping — a colour on the lift',
  topmark: 'topmark — one mark, several files',
  billet: 'billet — a slip for an address',
  gunnel: 'gunnel — what stays, what leaves',
  kevel: 'kevel — a file with a time on it',
  marline: 'marline — a caption on the still',
  fairlead: 'fairlead — an address, with a card',
  painter: 'painter — a colour on the discord card',
  oakum: 'oakum — a pack, filed one by one',
  scull: 'scull — a note rowed across',
  cleat: 'cleat — a tempo, not a drawer',
  lantern: 'lantern — a lamp for one sitting',
  splice: 'splice — two drafts, one card',
  quayage: 'quayage — a tally, not a vault',
  satchel: 'satchel — a pack, not a drawer',
  vitrine: 'vitrine — the public shelf',
  trammel: 'trammel — a timed drop',
  tiller: 'tiller — steer the discord card',
  lodestone: 'lodestone — a bearing, not a drawer',
  bosun: 'bosun — a watch, not a cabinet',
  hawse: 'hawse — a split, not a cabinet',
  deadeye: 'deadeye — a sitting, not a drawer',
  futtock: 'futtock — a colour ramp',
};

export const EXTRA_DESC = {
  cringle: 'Name the eye of a local file and file it. Discord unfurls the card. Large drops are warned, never refused.',
  bowline: 'Write a note in the tab. Filing turns it into a text drop. The /s link is the Discord card.',
  kedge: 'A pin in the desk table, with an optional local file in the share table. No size cutoff.',
  topping: 'Stamp a local file with a colour and a label, then file it. The card carries the colour.',
  topmark: 'Several local files land in the share table. Discord unfurls the pack note. Large packs are warned, never refused.',
  billet: 'An address on the links shelf, plus a one-line card Discord can unfurl. Not a file cabinet.',
  gunnel: 'Two columns — kept and sent — filed as one text drop. The /s link is the Discord card.',
  kevel: 'Pick a local file and a ready-by time. The bytes land in the share table. Discord unfurls the card. Large drops are warned, never refused.',
  marline: 'Burn a caption onto a still in the tab, then file the PNG. Image cards unfurl with the picture.',
  fairlead: 'Save a link on the quay and file a card Discord can unfurl. Optional cover. Not a cabinet.',
  painter: 'Pick a local file, write the card line, stamp a colour. Bytes land in the share table. Large drops are warned, never refused.',
  oakum: 'Each local file is written to the share database. The shelf keeps the list. Discord unfurls the first card.',
  scull: 'Open a local text file or type a note. Filing writes a real file into the share table and hands Discord a card.',
  cleat: 'A click in the tab. Filing the session writes a text note into the share table. Discord unfurls the card. Nothing is refused for size.',
  lantern: 'A warm timer for one sitting. File the note if you want a Discord card. Not a cabinet.',
  splice: 'Join two local texts and file the combined note. Discord unfurls /s. Large splices are warned, never cut.',
  quayage: 'A line tally that files as a receipt. Discord gets the card. Nothing is stored until you send it.',
  satchel: 'Pack local files into one parcel. Each file lands in the share database. Discord unfurls the pack. Large packs are warned, never refused.',
  vitrine: 'The public shelf of files already filed. Every card still unfurls on Discord.',
  trammel: 'Pick a local file, optional pass, optional ready-by. Bytes land in the share table. Discord unfurls /s. Slowness warning only.',
  tiller: 'Set the title, caption, and accent, then file a local file. Discord unfurls the card you steered. Large drops are warned, never refused.',
  lodestone: 'Save an address on the links shelf and file a text card Discord can unfurl. Not a cabinet.',
  bosun: 'A watch list in the tab. Filing writes one markdown drop. Discord unfurls the list. Not a vault drawer.',
  hawse: 'Split a bill in the tab. Filing writes the note, and an optional receipt, into the share database. Discord unfurls the card. Large slips are warned, never refused.',
  deadeye: 'A sitting timer. File the note if you want a Discord card. Not a cabinet.',
  futtock: 'Mix a colour ramp, then file it with an optional reference image. Discord takes the accent. Large references are warned, never refused.',
};
